### ISSUE TITLE
I have some questions

### ISSUE THREAD

**Issue by taki0112** [ghcollin/tftables#10]
I have some questions...

1.
```python
def input_transform(tbl_batch):
    labels = tbl_batch['non_nodule']
    data = tbl_batch['nodule']

    return truth, data

loader = tftables.load_dataset(filename='path/to/h5_file.h5',
                               dataset_path='/internal/h5/path',
                               input_transform=input_transform,
                               batch_size=16)
```
h5_file -> 'nodule', 'non_nodule' is key ...
What does `dataset_path` mean?
If my hdf5 file name is `taki.h5` and the path is `/home/data/lunit/taki.h5`

```python
filename = taki.h5
dataset_path = /home/data/lunit/
```

or 
```python
filename = /home/data/lunit/taki.h5
dataset_path = nodule
```
What is the correct answer?

2. 
```python
def input_transform(tbl_batch):
    labels = tbl_batch['non_nodule']
    data = tbl_batch['nodule']

    return truth, data

loader = tftables.load_dataset(filename='path/to/h5_file.h5',
                               dataset_path='/internal/h5/path',
                               input_transform=input_transform,
                               batch_size=16)

result = my_network(self.x, self.y)
# self.x = tf.placeholder(tf.float32, [16,68,68,68,3])
# self.y = tf.placeholder(tf.float32, [16,2])

with tf.Session() as sess:
    with loader.begin(sess):
        for _ in range(num_iterations): 
            truth_batch, data_batch = loader.dequeue()
            feed_dict = { self.x : data_batch, self.y : truth_batch }

            sess.run(result, feed_dict=feed_dict)
```

Is this possible?
Please answer

Thank you !

**Comment by ghcollin** [comment]
For your first question,
```python
filename = /home/data/lunit/taki.h5
dataset_path = /nodule
```
is correct, assuming that `nodule` is the name of your dataset (table or array) inside your HDF5 file.

For your second question, the `a` and `b` in 
```
    labels = tbl_batch['a']
    data = tbl_batch['b']
```
refer to the columns of a HDF5 table. If possible, you should reformat your dataset into a table with separate columns for the data and labels. You can refer to the `pytables` documentation to find out how to do this. If reformatting is not possible, the online documentation provides some examples on how to pull the label and data out of separate datasets.

You should follow the quick start example in the README as close as possible (or the other examples in the online docs). In your code, you refer to `self.x` and `self.y` which are not yet defined. You also call the `dequeue` function on every iteration. Remember that this function creates placeholders in your computational graph, so calling it more than once is redundant and can cause problems. Finally, you should avoid using the `feed_dict` method as it tends to be very slow, `tftables` handles the loading of the data for you.

**Comment by taki0112** [comment]
um...
Let's say I have h5 files((taki0.h5, taki1.h5, taki2.h5 ... etc)) in `/home/data/lunit/`

Then.. !
```python
dataset_path = /home/data/lunit/
filename_path = /home/data/lunit/taki0.h5 <- target file for load
```
Is that right ?

**Comment by ghcollin** [comment]
No, `dataset_path` refers to the _internal_ path to the dataset inside your HDF5 file. You can use the `h5dump` or `h5ls` commands to list/explore the HDF5 file. The `filename_path` refers to the location of the file in your filesystem. 

In addition, `tftables` can only read from one HDF5 file. It is not designed to read from multiple files at once. To do that, you'd have to collate your data into a single file.

**Comment by taki0112** [comment]
I open this [link](https://support.hdfgroup.org/HDF5/Tutor/cmdtoolview.html#h5ls)

but... I don't know what means `dataset_path`... how can I know this `dataset_path` ? 

sorry... plz help me.. !!!! 
Thank you !

**Comment by ghcollin** [comment]
The paths are the columns on the right hand side. Eg: `/label_non_nodule` is a dataset path. 

You may want to review how HDF5 files work. I recommend you write a python script using `pytables` to create a HDF5 file with groups, and arrays/tables within those groups. Then examine it using `h5dump`, and also write a python script to read it back in. 

Once you understand groups, the role of `dataset_path` will become much more clear. A path is needed to address datasets in HDF5 because of the potential presence of groups. (You can see that in your example, the root of the HDF5 file is a group and is denoted by `/`, hence the requirement for a leading slash)
