### ISSUE TITLE
Cannot use same FIFOLoader twice.

### ISSUE THREAD

**Issue by yngvem** [ghcollin/tftables#11]
I get an error whenever I try to use the same FIFOLoader twice. The error, as far as I can tell, comes from these lines:

    if self.monitor_thread is not None:
        raise Exception("This loader has already been started.")

and the fact that the monitor thread is only closed, but not set to None when `loader.stop(sess)` is called.

**Comment by ghcollin** [comment]
Unfortunately, the tensorflow FIFOQueue that FIFOLoader uses can't be restarted after it has been closed, so the loader can't be reused in its present form.

What's the use case that you want to restart the loader for? There may be another way to approach the problem.

**Comment by yngvem** [comment]
Nothing important, I was simply trying to understand how the tftables module works so I can use it nicely in my Masters project.
