### ISSUE TITLE
Is preprocessing and augmentation possible?

### ISSUE THREAD

**Issue by ibadami** [ghcollin/tftables#3]
Hi Thank you for this library. This is something exactly I was looking for. I have hdf5 file for PASCAL VOC dataset for object detection. In this file I have two dataset, one contains variable length images and other contains segmentation masks for each of the object category presented in the image.  I wish to feed the data in a following way.
Read image and corresponding masks, resize and augment them using custom warp function and then feed them in the FIFO queue for training. You can find the full question [here](http://stackoverflow.com/questions/42512951/dataflow-using-hdf5-dataset-in-tflearn). Could you please help me with this problem?

**Comment by ghcollin** [comment]
With 9fc5271587ac6f785bbc4ad76cab8793a765fe62, the quick start example in the readme file has a simpler interface for loading a dataset, with an explicit function for transforming (pre-processing) data before it is loaded into the queue. 

I'm leaving this ticket open until I write more thorough documentation.
