### ISSUE TITLE
Multiple h5 files

### ISSUE THREAD

**Issue by efrank2** [ghcollin/tftables#4]
My dataset is formatted as a few dozen h5 files instead of one h5 with internal directories. Is it possible to load them into one queue without merging them into one file?

**Comment by ghcollin** [comment]
Sorry for the late reply.

If your dataset has each input for your model as a different file then you should just be able to load each dataset with ordered access turned on. The output of each loader can then be put into your model, eg:

```python
example_loader = tftables.load_dataset(filename='examples.h5',
                                   dataset_path='example_array',
                                   batch_size=20,
                                   ordered=True
)
label_loader = tftables.load_dataset(filename='labels.h5',
                                   dataset_path='label_array',
                                   batch_size=20,
                                   ordered=True
)
example_batch = example_loader.dequeue()
label_batch = label_loader.dequeue()
output = my_model(example_batch, label_batch)
```

You should test this, as I've never tried this myself. I recommend you combine your files into one h5 file with a table if you have performance issues, as this access pattern could be problematic on a RAID array.

If your dataset has multiple h5 files for each class (eg; `cat_images.h5` and `dog_images.h5`), then things get a bit more complicated. 

If the number of classes is less than your batch size, then you could load each h5 file individually then use `tf.concat` to merge them into one larger batch. Eg; your target batch size is 20, and you have 4 classes, then you could load each file with a batch size of 5 and concatenate them into a batch size of 20. 

If the number of classes exceeds your batch size, you'll either have to use some method of randomly (or systematically) gathering a batch form multiple sources, or combine your files into one large h5 file. Unfortunately tftables wasn't designed for this use case.
