### ISSUE TITLE
hdf5 files created by h5py

### ISSUE THREAD

**Issue by weiliu620** [ghcollin/tftables#5]
Does tftables support hdf5 files created by h5py? I have such files that contain multiple datasets (that is, numpy arrays) in them. 

It seems tftables is built on top of 'tables', which is different from h5py library.

**Comment by ghcollin** [comment]
It should. Both PyTables and h5py are interfaces to the same HDF5 C library. I'm not 100% on how well PyTables handles heterogeneous storage that doesn't comply to the HDF5 table format, but PyTables was designed to handle any kind of HDF5 file. The best way to find out would be to try it.
